Update patch set 1
Patch Set 1: Code-Review-1

This patch breaks compilation.
Second declaration of "device_support_hwfde" needs to be under lineage namespace.

error: system/vold/Android.bp:172:29: unrecognized property "product_variables.device_support_hwfde"

Patch-set: 1
Reviewer: Pranav Vashi <6360@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Code-Review=-1