Update patch set 1
Patch Set 1:

Breaks build for me:

system/vold/Ext4.cpp: In static member function 'static int Ext4::doMount(const char*, const char*, bool, bool, bool, bool, const char*)':
system/vold/Ext4.cpp:78:27: error: 'AID_MEDIA_RW' was not declared in this scope

Patch-set: 1
Reviewer: Andrew Bartholomew <4820@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0